"""fix primary key issue on purchase table

Revision ID: 142e50607439
Revises: 58ce98250368
Create Date: 2015-05-28 16:19:57.930069

"""

# revision identifiers, used by Alembic.
revision = '142e50607439'
down_revision = '58ce98250368'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
