"""dummy migration

Revision ID: 15d959a2cf64
Revises: 30a8c36ecc26
Create Date: 2015-05-19 06:51:03.614443

"""

# revision identifiers, used by Alembic.
revision = '15d959a2cf64'
down_revision = '30a8c36ecc26'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_color', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'favorite_color')
    ### end Alembic commands ###
