"""bcryptaddition migration

Revision ID: 1c77c4fee6c8
Revises: 30a8c36ecc26
Create Date: 2015-05-19 07:25:46.874684

"""

# revision identifiers, used by Alembic.
revision = '1c77c4fee6c8'
down_revision = '30a8c36ecc26'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
