"""empty message

Revision ID: 2389ff4b8982
Revises: 8d1d1c0727
Create Date: 2015-05-23 23:08:45.177017

"""

# revision identifiers, used by Alembic.
revision = '2389ff4b8982'
down_revision = '8d1d1c0727'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_path', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'image_path')
    ### end Alembic commands ###
