"""empty message

Revision ID: 278dff4fbda8
Revises: 3445085f76d3
Create Date: 2015-06-01 21:05:27.615634

"""

# revision identifiers, used by Alembic.
revision = '278dff4fbda8'
down_revision = '3445085f76d3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('image_path', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'image_path')
    ### end Alembic commands ###
