"""Added Course and Student tables

Revision ID: 2a242c3a5c59
Revises: 86a9cbcf17a
Create Date: 2015-05-27 21:31:11.810939

"""

# revision identifiers, used by Alembic.
revision = '2a242c3a5c59'
down_revision = '86a9cbcf17a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_enrolled', sa.DateTime(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('parent_first_name', sa.String(), nullable=False),
    sa.Column('parent_last_name', sa.String(), nullable=False),
    sa.Column('parent_email', sa.String(), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('second_parent_first_name', sa.String(), nullable=True),
    sa.Column('second_parent_last_name', sa.String(), nullable=True),
    sa.Column('second_parent_email', sa.String(), nullable=True),
    sa.Column('second_parent_phone', sa.Integer(), nullable=True),
    sa.Column('medical_issues', sa.String(), nullable=True),
    sa.Column('custody_issues', sa.String(), nullable=True),
    sa.Column('release_people', sa.String(), nullable=True),
    sa.Column('referral_source', sa.String(), nullable=True),
    sa.Column('student_email', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('fully_paid', sa.Boolean(), nullable=False),
    sa.Column('amount_paid', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    ### end Alembic commands ###
