"""empty message

Revision ID: 3445085f76d3
Revises: 538e89258708
Create Date: 2015-06-01 16:18:03.957637

"""

# revision identifiers, used by Alembic.
revision = '3445085f76d3'
down_revision = '538e89258708'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('age_range', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'age_range')
    ### end Alembic commands ###
