"""empty message

Revision ID: 3606e62e2fe1
Revises: None
Create Date: 2015-05-21 14:15:02.284376

"""

# revision identifiers, used by Alembic.
revision = '3606e62e2fe1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
