"""Made most course information nullable

Revision ID: 48a9fe99fc8
Revises: 2a242c3a5c59
Create Date: 2015-05-27 22:05:52.301982

"""

# revision identifiers, used by Alembic.
revision = '48a9fe99fc8'
down_revision = '2a242c3a5c59'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'course_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('courses', 'course_instructor',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('courses', 'course_location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('courses', 'course_num_students',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('courses', 'course_price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('courses', 'course_start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'course_start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('courses', 'course_price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('courses', 'course_num_students',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('courses', 'course_location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('courses', 'course_instructor',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('courses', 'course_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ### end Alembic commands ###
