"""adding price cents

Revision ID: 4d4312a1da78
Revises: 538e89258708
Create Date: 2015-05-29 13:25:26.338223

"""

# revision identifiers, used by Alembic.
revision = '4d4312a1da78'
down_revision = '538e89258708'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('price_cents', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'price_cents')
    ### end Alembic commands ###
