"""second attemempt to fix primary key issue on purchase table

Revision ID: 538e89258708
Revises: 142e50607439
Create Date: 2015-05-28 16:25:22.573406

"""

# revision identifiers, used by Alembic.
revision = '538e89258708'
down_revision = '142e50607439'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
