"""added dates, payment methods, notes to Purchase

Revision ID: 58ce98250368
Revises: 36ec5b6dfe16
Create Date: 2015-05-28 16:10:41.558943

"""

# revision identifiers, used by Alembic.
revision = '58ce98250368'
down_revision = '36ec5b6dfe16'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('date_purchased', sa.DateTime(), nullable=False))
    op.add_column('purchases', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('purchases', sa.Column('payment_method', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'payment_method')
    op.drop_column('purchases', 'notes')
    op.drop_column('purchases', 'date_purchased')
    ### end Alembic commands ###
