"""empty message

Revision ID: 86a9cbcf17a
Revises: 2389ff4b8982
Create Date: 2015-05-27 16:37:24.682098

"""

# revision identifiers, used by Alembic.
revision = '86a9cbcf17a'
down_revision = '2389ff4b8982'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_title', sa.String(length=128), nullable=False),
    sa.Column('course_description', sa.String(), nullable=False),
    sa.Column('course_location', sa.String(), nullable=False),
    sa.Column('course_start_date', sa.DateTime(), nullable=False),
    sa.Column('course_end_date', sa.DateTime(), nullable=True),
    sa.Column('course_duration', sa.Float(), nullable=True),
    sa.Column('class_start_time', sa.Time(), nullable=True),
    sa.Column('class_end_time', sa.Time(), nullable=True),
    sa.Column('class_duration', sa.Time(), nullable=True),
    sa.Column('course_price', sa.Float(), nullable=False),
    sa.Column('course_num_students', sa.Integer(), nullable=False),
    sa.Column('course_instructor', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instructors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('hired_on', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instructors')
    op.drop_table('courses')
    ### end Alembic commands ###
