"""empty message

Revision ID: 8d1d1c0727
Revises: 3606e62e2fe1
Create Date: 2015-05-21 18:00:53.443895

"""

# revision identifiers, used by Alembic.
revision = '8d1d1c0727'
down_revision = '3606e62e2fe1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'registered_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'registered_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    ### end Alembic commands ###
